replicaCount: 1

image:
  repository: quakewatch2
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

serviceAccount:
  create: true
  name: quakewatch2-sa

ingress:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}
