apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "quakewatch2.fullname" . }}-cron
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              args:
                - python
                - cron_task.py
          restartPolicy: OnFailure
