apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "quakewatch2.fullname" . }}-cron
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: quakewatch2
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["python", "app.py"]
          restartPolicy: OnFailure
