apiVersion: v1
kind: Service
metadata:
  name: quakewatch2-quakewatch2
  namespace: quakewatch2
  labels:
    app: quakewatch2
spec:
  selector:
    app: quakewatch2
  ports:
    - name: http                # 👈 this must match the endpoint's "port"
      port: 80
      targetPort: 8000