apiVersion: v1
kind: Service
metadata:
  name: quakewatch2-quakewatch2
  namespace: quakewatch2
  labels:
    app.kubernetes.io/name: quakewatch2
spec:
  selector:
    app: quakewatch2
  ports:
    - name: http        # <-- This must match the port name in the ServiceMonitor
      port: 80
      targetPort: 8000
