apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quakewatch2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/marina060708/quakewatch2
    targetRevision: main
    path: chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: quakewatch2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
