apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: quakewatch2-monitor
  namespace: monitoring  # Adjust if your Prometheus Operator is in another namespace
  labels:
    release: prometheus-stack  # Must match Prometheus's selector label
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: quakewatch2
  namespaceSelector:
    matchNames:
      - quakewatch2
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
